framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            sync_starred_repos:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/sync_starred_repos'
                options:
                    exchange:
                        name: banditore.sync_starred_repos
                        type: direct
                    queues:
                        banditore.sync_starred_repos: ~

            sync_versions:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%/sync_versions'
                options:
                    exchange:
                        name: banditore.sync_versions
                        type: direct
                    queues:
                        banditore.sync_versions: ~

            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            'App\Message\StarredReposSync': sync_starred_repos
            'App\Message\VersionsSync': sync_versions

        buses:
            command_bus:
                middleware:
                    - doctrine_ping_connection
                    - doctrine_close_connection

when@test:
    framework:
        messenger:
            transports:
                sync_starred_repos: 'in-memory://'
                sync_versions: 'in-memory://'
